
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: ""

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jazz"
title: "Jazz"
description: "jazzy."
keywords: "jazz, jazzy, rap, hip-hop"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "/img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."
  - text: "Lost in thought made me question my concsiousness."

me-img: "/img/jazz.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: false
reddit-share: false
google-plus-share: false
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/8-10-16.jpg"
    date: "August 10, 2016"
    description: "Club Tequila!"
  - image: "/img/timeline/8-9-16.jpg"
    date: "August 9, 2016"
    description: "Komiposi Show hosted by Ayo Tamz"

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "everythingprofit@yahoo.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Jazz is a new artist out West Texas."
author_blurb_image: "/img/jazz.jpg"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/432jazz"
  - title: "instagram"
    url: "https://instagram.com/432jazz"
  - title: "soundcloud"
    url: "https://soundcloud.com/432jazz"
#  - title: "github"
#    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/jazzy.jpg"

##################
# GPG on Keybase #
##################

keybase-username: 
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
